name: Test extension
on: pull_request
jobs:
  build:
    name: Exec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: actions/setup-node@master
      - run: npm install
      - run: echo $GITHUB_REF
      - run: sed -i 's/VERSION_VALUE/0.1.1/' package.json
      - run: npm run exec
