name: Release
on: 
  release:
    types: published 
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run exec
    - name: Publish
      uses: artemnovichkov/action-zem@master
      env:
        ZEM_TOKEN: ${{ secrets.ZEM_TOKEN }}
      with:
        args: publish
